---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: az-vm
  namespace: flux-system
spec:
  approvePlan: "auto"
  interval: 2m
  path: ./terraform/vm
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
    namespace: flux-system
  vars:
  - name: name
    value: "gitopsdays"
  - name: location
    value: "Norway East"
  varsFrom:
    - kind: Secret
      name: vmsecrets

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
