apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dependency-demo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./examples/dependency
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system